name: 'action-cassandra-start-and-stop'
description: 'Start/stop cassandra server for build test'
inputs:
  cassandra_version:
    description: 'Cassandra server version'
    required: false
    default: '4.1.3'
  cassandra_container_name:
    description: 'container name'
    default: 'cassandra-container'
  stop:
    description: 'Stop Cassandra server'
    required: false
    type: boolean
  cassandra_container_memory:
    description: 'Set container max mem for cassandra server'
    required: false
    default: '768m'
  cassandra_jvm_opts:
    description: 'Set cassandra extra jmv options'
    required: false
    default: '-Xms512m -Xmx512m'
outputs:
  cassandra_port:
    description: 'Random host port on which Cassandra is bound.'
    value: ${{ steps.get-port.outputs.cassandra_host_port }}
runs:
  using: 'composite'
  steps:
    - name: Use local cassandra if possible or Docker otherwise
      # Use local cassandra if possible (and skip all all steps) or use docker (with subsequent steps)
      id: prep
      shell: bash
      env:
        STOP: ${{ inputs.stop }}
      # Note: Look at the runner-setup-cassandra repository for details about used scripts.
      run: |
        RUNNER_SUFFIX=$(echo "$RUNNER_NAME" | grep -oE '[0-9]+$')
        SCRIPT_DIR="$HOME/cassandra-$RUNNER_SUFFIX"
        echo "script_dir=$SCRIPT_DIR" >> $GITHUB_OUTPUT

        if [[ -n "$RUNNER_SUFFIX" ]] && \
           [[ -f "$SCRIPT_DIR/cassandra-port.sh" ]] && \
           [[ -f "$SCRIPT_DIR/run-cassandra.sh" ]]; then

            echo "Do not use docker."
            echo "use_docker=false" >> $GITHUB_OUTPUT
            if [[ "$STOP" == "true" ]]; then
                echo "Do not stop cassandra for next job reuse."
            else
                echo "Reusing the cassandra of runner $RUNNER_NAME in $SCRIPT_DIR"

                "$SCRIPT_DIR/run-cassandra.sh" || true  # Ignore failures for now: we should fix the runner and its scripts rather than
                                                        # fallback to docker.
                if [[ -f "$SCRIPT_DIR/play-cql.sh" ]]; then
                    "$SCRIPT_DIR/play-cql.sh"
                fi
            fi
        else
            echo "Using docker"
            COMMIT_SHA=${{ github.sha }}
            COMMIT_SHORTREF=${COMMIT_SHA::8}
            CASSANDRA_CONTAINER_NAME="${{ inputs.cassandra_container_name }}-${{ github.event.repository.name }}-${COMMIT_SHORTREF}"
            echo "Container name is $CASSANDRA_CONTAINER_NAME"
            echo "dcass_container_name=${CASSANDRA_CONTAINER_NAME}" >> $GITHUB_OUTPUT
            echo "use_docker=true" >> $GITHUB_OUTPUT
        fi

    - name: Start Cassandra container
      if: steps.prep.outputs.use_docker == 'true' && !inputs.stop
      run: |
        if [ "$(docker ps -aq -f name=${{ steps.prep.outputs.dcass_container_name }})" ]; then
            docker rm -f ${{ steps.prep.outputs.dcass_container_name }}
        fi
        mkdir -p ${RUNNER_TEMP}/cassandra_datadir
        docker run -d --name ${{ steps.prep.outputs.dcass_container_name }} \
          -m ${{ inputs.cassandra_container_memory }} \
          -e JVM_EXTRA_OPTS="${{ inputs.cassandra_jvm_opts }}" \
          -p 9042 \
          cassandra:${{ inputs.cassandra_version }}
      shell: bash

    - name: Get cassandra host port number
      id: get-port
      if: '!inputs.stop'
      shell: bash
      env:
        STOP: ${{ inputs.stop }}
        SCRIPT_DIR: ${{ steps.prep.outputs.script_dir }}
      run: |
        if [[ "${{ steps.prep.outputs.use_docker }}" == "true" ]]; then
          CASSANDRA_HOST_PORT=$(
              docker inspect ${{ steps.prep.outputs.dcass_container_name }} \
                --format '{{ (index (index .NetworkSettings.Ports "9042/tcp") 0).HostPort }}'
          )
        else
          CASSANDRA_HOST_PORT=$("$SCRIPT_DIR/cassandra-port.sh")
        fi
        echo "cassandra_host_port=${CASSANDRA_HOST_PORT}" >> $GITHUB_OUTPUT

    - name: Wait for Cassandra to start
      if: steps.prep.outputs.use_docker == 'true' && !inputs.stop
      run: |
        timeout_seconds=120 
        start_time=$(date +%s) 

        check_cassandra() {
              if command -v cqlsh >/dev/null 2>&1; then
                  cqlsh localhost ${{ steps.get-port.outputs.cassandra_host_port }} -e "DESCRIBE KEYSPACES;"
              else
                  docker exec ${{ steps.prep.outputs.dcass_container_name }} cqlsh -e "DESCRIBE KEYSPACES;"
              fi
        }

        while ! check_cassandra; do
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))

            if [ "$elapsed_time" -ge "$timeout_seconds" ]; then
                echo "Timeout: Cassandra is not ready within the specified timeout."
                docker rm -f ${{ steps.prep.outputs.dcass_container_name }}
                exit 1
            fi

            sleep 2
        done
        echo "Cassandra is ready."
      shell: bash

    - name: Delete cassandra container
      if: steps.prep.outputs.use_docker == 'true' && inputs.stop
      run: |
        if [ "$(docker ps -aq -f name=${{ steps.prep.outputs.dcass_container_name }})" ]; then
            docker rm -f ${{ steps.prep.outputs.dcass_container_name }}
        fi
      shell: bash
